changelog = true
gitSourceBranch = "main"

[docusaurus]
tagline = "Performance measuring tool for Roblox"

[[navbar.items]]
href = "https://discord.gg/nhDpg96Srt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://discord.gg/luau"
label = "Luau Discord"
position = "right"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "All platforms supported"
description = "Unlike its namesake FRAPS and the built in performance menu, RoFraps supports ALL platforms."

[[home.features]]
title = "Show more than just FPS"
description = "RoFraps calculates more than just the current FPS, it also calculates average FPS, minimum FPS, maximum FPS, 1% lows, and 0.1% lows."

[[home.features]]
title = "Accurate FPS calculation"
description = "RoFraps uses the most accurate method of calculating FPS on Roblox."

[footer]
style = "dark"
copyright = "Built with Moonwave and Docusaurus"
